In [1]:
import pandas as pd
import numpy as np

In [3]:
raw_data = {
    "Roll_No":[101,102,103,104,104,105,106,107,108,109,110,111],
    "Name":["Aman","Bhavna","Chetan","Diya","Diya","Eshan","Farah","Gopal","Heena","Irfan","Jatin","Kiran"],
    "Gender":["Male","Female","Male","Female","Female","Male","Female","Male","Female","Male","Male","Female"],
    "Marks":[78,85,np.nan,92,92,999,66,73,88,np.nan,59,81],
    "Attendance":["85%","90%","80 percent","95%","95%","60%","72%","88%",None,"91%","77%","89%"],
    "Exam_Date":["2026-02-01","01/02/2026","2026.02.01","Feb 1 2026","Feb 1 2026","2026-02-01",
                "2026/02/01","2026-02-01","02-01-2026","2026-02-01","invalid_date","2026-02-01"]
}
csv_raw = pd.DataFrame(raw_data)
raw_csv_path="student_marks_raw.csv"
csv_raw.to_csv(raw_csv_path,index=False)
print("raw Dataset saved as:", raw_csv_path)
csv_raw

raw Dataset saved as: student_marks_raw.csv

    Roll_No    Name  Gender  Marks  Attendance     Exam_Date
0       101    Aman    Male   78.0         85%    2026-02-01
1       102  Bhavna  Female   85.0         90%    01/02/2026
2       103  Chetan    Male    NaN  80 percent    2026.02.01
3       104    Diya  Female   92.0         95%    Feb 1 2026
4       104    Diya  Female   92.0         95%    Feb 1 2026
5       105   Eshan    Male  999.0         60%    2026-02-01
6       106   Farah  Female   66.0         72%    2026/02/01
7       107   Gopal    Male   73.0         88%    2026-02-01
8       108   Heena  Female   88.0        None    02-01-2026
9       109   Irfan    Male    NaN         91%    2026-02-01
10      110   Jatin    Male   59.0         77%  invalid_date
11      111   Kiran  Female   81.0         89%    2026-02-01

In [4]:
df = pd.read_csv("student_marks_raw.csv")
df.head()

   Roll_No    Name  Gender  Marks  Attendance   Exam_Date
0      101    Aman    Male   78.0         85%  2026-02-01
1      102  Bhavna  Female   85.0         90%  01/02/2026
2      103  Chetan    Male    NaN  80 percent  2026.02.01
3      104    Diya  Female   92.0         95%  Feb 1 2026
4      104    Diya  Female   92.0         95%  Feb 1 2026

In [5]:
print("Duplicates(count):",df.duplicated().sum())
print("Shape before removing duplicates:",df.shape)
df = df.drop_duplicates()
print("Shape after removing duplicates:",df.shape)
df

Duplicates(count): 1
Shape before removing duplicates: (12, 6)
Shape after removing duplicates: (11, 6)

    Roll_No    Name  Gender  Marks  Attendance     Exam_Date
0       101    Aman    Male   78.0         85%    2026-02-01
1       102  Bhavna  Female   85.0         90%    01/02/2026
2       103  Chetan    Male    NaN  80 percent    2026.02.01
3       104    Diya  Female   92.0         95%    Feb 1 2026
5       105   Eshan    Male  999.0         60%    2026-02-01
6       106   Farah  Female   66.0         72%    2026/02/01
7       107   Gopal    Male   73.0         88%    2026-02-01
8       108   Heena  Female   88.0         NaN    02-01-2026
9       109   Irfan    Male    NaN         91%    2026-02-01
10      110   Jatin    Male   59.0         77%  invalid_date
11      111   Kiran  Female   81.0         89%    2026-02-01

In [7]:
df["Attendance"]=(
    df["Attendance"]
    .astype(str)
    .str.lower()
    .str.replace("%","",regex=False)
    .str.replace("percent","",regex=False)
    .str.strip()
)
df["Attendance"] = pd.to_numeric(df["Attendance"],errors="coerce")
print(df[["Attendance"]].head(10))
print("\nMissing in Attendance after conversion:",df["Attendance"].isnull().sum())

    Attendance
0         85.0
1         90.0
2         80.0
3         95.0
5         60.0
6         72.0
7         88.0
8          NaN
9         91.0
10        77.0

Missing in Attendance after conversion: 1

In [9]:
df.loc[df["Marks"]>100,"Marks"]=np.nan
marks_mean = df["Marks"].mean(skipna=True)
attendance_median = df["Attendance"].median(skipna=True)
df["Marks"]=df["Marks"].fillna(round(marks_mean,2))
df["Attendance"]=df["Attendance"].fillna(attendance_median)
print("Marks mean:",marks_mean)
print("Attendance median:",attendance_median)
df.isnull().sum()

Marks mean: 77.75
Attendance median: 86.5

Roll_No       0
Name          0
Gender        0
Marks         0
Attendance    0
Exam_Date     0
dtype: int64

In [10]:
df["Gender"]=df["Gender"].map({"Male":0,"Female":1})
df[["Gender"]].head()

   Gender
0       0
1       1
2       0
3       1
5       0

In [12]:
print("Final shape:",df.shape)
print("\nMissing Values:\n",df.isnull().sum())
print("\nData types:\n",df.dtypes)
df.head(10)

Final shape: (11, 6)

Missing Values:
 Roll_No       0
Name          0
Gender        0
Marks         0
Attendance    0
Exam_Date     0
dtype: int64

Data types:
 Roll_No         int64
Name           object
Gender          int64
Marks         float64
Attendance    float64
Exam_Date      object
dtype: object

    Roll_No    Name  Gender  Marks  Attendance     Exam_Date
0       101    Aman       0  78.00        85.0    2026-02-01
1       102  Bhavna       1  85.00        90.0    01/02/2026
2       103  Chetan       0  77.75        80.0    2026.02.01
3       104    Diya       1  92.00        95.0    Feb 1 2026
5       105   Eshan       0  77.75        60.0    2026-02-01
6       106   Farah       1  66.00        72.0    2026/02/01
7       107   Gopal       0  73.00        88.0    2026-02-01
8       108   Heena       1  88.00        86.5    02-01-2026
9       109   Irfan       0  77.75        91.0    2026-02-01
10      110   Jatin       0  59.00        77.0  invalid_date

In [13]:
df["Exam_Date"]=pd.to_datetime(df["Exam_Date"],errors="coerce",dayfirst=True)
most_common_date = df["Exam_Date"].mode()[0]
df["Exam_Date"]=df["Exam_Date"].fillna(most_common_date)
df["Exam_Date"]=df["Exam_Date"].dt.strftime("%Y-%m-%d")
df["Exam_Date"].dtype
df

    Roll_No    Name  Gender  Marks  Attendance   Exam_Date
0       101    Aman       0  78.00        85.0  2026-02-01
1       102  Bhavna       1  85.00        90.0  2026-02-01
2       103  Chetan       0  77.75        80.0  2026-02-01
3       104    Diya       1  92.00        95.0  2026-02-01
5       105   Eshan       0  77.75        60.0  2026-02-01
6       106   Farah       1  66.00        72.0  2026-02-01
7       107   Gopal       0  73.00        88.0  2026-02-01
8       108   Heena       1  88.00        86.5  2026-01-02
9       109   Irfan       0  77.75        91.0  2026-02-01
10      110   Jatin       0  59.00        77.0  2026-02-01
11      111   Kiran       1  81.00        89.0  2026-02-01